import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import { MenuLateralWrapper } from "@/componentes/menu_Lateral/menu_Wrapper";

export const metadata: Metadata = {
  title: "Controle de Gastos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{

  return (
    <html lang="en">
      <body>
      <Suspense fallback={<div>Loading...</div>}>
          <MenuLateralWrapper />
        </Suspense>
        <main>{children}</main>
      </body>
    </html>
  );
}
